"""
src/launcher_macos.py

Create a double-clickable launcher for a command-line install.

The app is installed with a package manager, which is cheap to ship and needs
no Apple Developer account, but leaves the user opening a terminal every time
they want to take notes in a meeting. That is a poor trade for something used
weekly.

A small .app bundle fixes it, and the reason it can is worth stating because
it is the whole basis of this approach: **Gatekeeper only enforces on files
carrying `com.apple.quarantine`**, which is applied to things downloaded from
the internet. A bundle created here, on this machine, has no such attribute.
`spctl` still reports it as rejected -- it genuinely has no usable signature --
but `open` launches it without complaint.

So a locally generated launcher behaves like an installed app: Dock, Spotlight,
Launchpad, double-click. Without a Developer ID, without notarization, and
without the "Open Anyway" trip through System Settings that an unsigned
*downloaded* app now requires on macOS 15 and later.

The bundle holds a shell script, not a copy of the program. Updating through
the package manager therefore updates what the icon launches, with no
reinstall.
"""

import os
import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path
from typing import Optional

APP_NAME = "EchoAI Helper"
BUNDLE_ID = "ai.echo365.helper"

# ~/Applications, not /Applications: no administrator rights, and it is the
# conventional home for per-user apps. Spotlight and Launchpad index it.
DEFAULT_LOCATION = Path.home() / "Applications"

LAUNCH_SCRIPT = """#!/bin/bash
# Generated by EchoAI Helper. Edit the install rather than this file.
set -e

PYTHON="{python}"
MODULE="{module}"
WORKDIR="{workdir}"

cd "$WORKDIR"

# A double-clicked app inherits a minimal PATH -- /usr/bin:/bin:/usr/sbin:/sbin
# -- and nothing from a shell profile, because no shell ran. Anything installed
# by Homebrew is therefore invisible, which is how a launcher that worked from
# a terminal died on startup looking for ffmpeg. Both Homebrew prefixes, since
# Apple Silicon and Intel differ.
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

if [ ! -x "$PYTHON" ]; then
  osascript -e 'display alert "EchoAI Helper" message "The Python environment \
this launcher points at has gone. Reinstall, then run --install-launcher again."'
  exit 1
fi

# Log somewhere findable: a GUI launch has no terminal to print to, so
# without this a crash on startup leaves nothing behind to look at.
LOG="$HOME/Library/Logs/EchoAI Helper.log"
mkdir -p "$(dirname "$LOG")"
echo "--- launched $(date) ---" >> "$LOG"

# -u because a GUI launch has no terminal: Python would buffer stdout and the
# log would stay empty until the process exited, which is exactly when it is
# least useful.
exec "$PYTHON" -u -m "$MODULE" >> "$LOG" 2>&1
"""


def bundle_path(location: Optional[Path] = None) -> Path:
    return (location or DEFAULT_LOCATION) / f"{APP_NAME}.app"


def install(python: Optional[str] = None, module: Optional[str] = None,
            location: Optional[Path] = None, progress=print) -> Path:
    """
    Write the launcher bundle and return where it went.

    Records the interpreter currently in use, so the icon launches the same
    install the user just set up.

    Launches a module rather than a script path. A checkout has main.py sitting
    at the project root; a wheel does not -- the code lands in site-packages
    and there is no project root to point at. `-m src.app` is the one form that
    resolves in both.
    """
    python = python or sys.executable
    package = Path(__file__).resolve().parent
    project = package.parent
    module = module or "src.app"

    app = bundle_path(location)
    macos_dir = app / "Contents" / "MacOS"
    resources = app / "Contents" / "Resources"

    if app.exists():
        shutil.rmtree(app)
    macos_dir.mkdir(parents=True)
    resources.mkdir(parents=True)

    info = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": "launch",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "1.0",
        "CFBundleVersion": "1",
        "LSMinimumSystemVersion": "13.0",
        # Without this the launcher shows up as a second Dock icon alongside
        # the Tk window's own.
        "LSUIElement": False,
        "NSHighResolutionCapable": True,
        # Spoken to the user when macOS asks for the microphone. Vague system
        # wording here reads like malware; say what it is actually for.
        "NSMicrophoneUsageDescription":
            "EchoAI Helper transcribes what you say during a meeting.",
    }

    icon = package / "resources" / "images" / "icon.icns"
    if icon.exists():
        shutil.copy(icon, resources / "icon.icns")
        info["CFBundleIconFile"] = "icon"

    with open(app / "Contents" / "Info.plist", "wb") as f:
        plistlib.dump(info, f)

    launcher = macos_dir / "launch"
    launcher.write_text(LAUNCH_SCRIPT.format(
        python=python, module=module, workdir=str(project)))
    launcher.chmod(launcher.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    # Ask Launch Services to notice it now rather than whenever it next
    # rescans, so the icon is usable immediately.
    _register(app)

    progress(f"Installed {app}")
    progress("It is in Launchpad and Spotlight; drag it to the Dock to keep it.")
    return app


def uninstall(location: Optional[Path] = None, progress=print) -> bool:
    app = bundle_path(location)
    if not app.exists():
        progress("No launcher installed.")
        return False
    shutil.rmtree(app)
    progress(f"Removed {app}")
    return True


def is_installed(location: Optional[Path] = None) -> bool:
    return bundle_path(location).exists()


def _register(app: Path) -> None:
    lsregister = ("/System/Library/Frameworks/CoreServices.framework/Versions/"
                  "A/Frameworks/LaunchServices.framework/Versions/A/Support/"
                  "lsregister")
    if not os.path.exists(lsregister):
        return
    try:
        subprocess.run([lsregister, "-f", str(app)],
                       capture_output=True, timeout=20)
    except Exception:
        # Cosmetic only: the bundle works regardless, Launch Services will
        # pick it up on its own schedule.
        pass
